<?php


function send_post($post_url,$post_data,$coo,$refer)
 {
  $ch = curl_init();
  //curl_setopt($ch, CURLOPT_PROXY, «http://192.168.2.600:2323″);
  curl_setopt($ch, CURLOPT_URL, $post_url);
  curl_setopt($ch, CURLOPT_HEADER,1);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
  curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
  curl_setopt($ch, CURLOPT_REFERER, $refer );
  curl_setopt($ch, CURLOPT_COOKIE,$coo);
  curl_setopt($ch, CURLOPT_POST, true);
  curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
  curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 100);
  curl_setopt($ch, CURLOPT_USERAGENT, "HTTPTool/1.0");
  curl_setopt($ch, CURLOPT_VERBOSE,1);
  $data = curl_exec($ch);
  //echo "======================================= 1 \n";
  $header_size = curl_getinfo($ch,CURLINFO_HEADER_SIZE);
  //echo "======================================= 2 \n";
  $result['header'] = substr($data, 0, $header_size);
//  echo "======================================= 3 \n";
  echo  $result['body'] = substr( $data, $header_size );
  echo "======================================== 4 \n";
  $result['body'] = str_replace(' ','+',$result['body']);
  
  $output = fopen("outtt.txt", "w+");
  fwrite($output,base64_decode($result['body']));
  fclose($output);

  $output = fopen("outtt.txt", "r+");
  echo $contents = fread($output, filesize("outtt.txt"));
  fclose($output);

  $output = fopen("outtt.txt", "r+");
  echo $contents = fgets($output);
  fclose($output);

  curl_close($ch);
  return $type;
 }


 $pd = "MIAGCSqGSIb3DQEHAqCAMIACAQExDDAKBgYqhQMCAgkFADCABgkqhkiG9w0BBwGggCSABIIB0zw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IndpbmRvd3MtMTI1MSI/Pg0KPENvbGxhdEF1dG8+DQogICAgPFJlcXVlc3Q+DQogICAgICAgIDxJZD4xMjM0NTY3ODkwLUFCQ0RFRkdIPC9JZD4NCiAgICAgICAgPFR5cGVDb2RlPjE8L1R5cGVDb2RlPg0KICAgICAgICA8QXV0aD4NCiAgICAgICAgICAgIDxNZW1iZXJDb2RlPjAwMDFaWjAwMDAwMDwvTWVtYmVyQ29kZT4NCiAgICAgICAgICAgIDxVc2VyPjAwMDFaWjAwMDAwMjwvVXNlcj4NCiAgICAgICAgICAgIDxQYXNzd29yZD5QYXNzd29yZDwvUGFzc3dvcmQ+DQogICAgICAgIDwvQXV0aD4NCiAgICAgICAgPENvbnRlbnRzPg0KICAgICAgICAgICAgPFZJTj5XQkExMjM0NTY3ODkwMTIzNDwvVklOPg0KICAgICAgICAgICAgPERvY051bT4xMVRDMTExMTExPC9Eb2NOdW0+DQogICAgICAgIDwvQ29udGVudHM+DQogICAgPC9SZXF1ZXN0Pg0KPC9Db2xsYXRBdXRvPg0KAAAAAAAAoIIJhTCCCYEwggkwoAMCAQICChdQ9UkAAAAAKCkwCAYGKoUDAgIDMIIBSzEYMBYGBSqFA2QBEg0xMDIxNjAyODU1MjYyMRowGAYIKoUDA4EDAQESDDAwMTY1NTA0NTQwNjEmMCQGA1UECQwd0YPQuy4g0JouINCd0LDRgdGL0YDQuCDQtC4gMjgxGzAZBgkqhkiG9w0BCQEWDGNhQHRheG5ldC5ydTELMAkGA1UEBhMCUlUxMzAxBgNVBAgMKjE2INCg0LXRgdC/0YPQsdC70LjQutCwINCi0LDRgtCw0YDRgdGC0LDQvTEVMBMGA1UEBwwM0JrQsNC30LDQvdGMMR4wHAYDVQQKDBXQl9CQ0J4g0KLQsNC60YHQndC10YIxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEjMCEGA1UEAwwa0KPQpiDQl9CQ0J4g0KLQsNC60YHQndC10YIwHhcNMTMwNzE3MTIzMDAwWhcNMTQwNzE3MTIzMTAwWjCCAjIxFjAUBgUqhQNkAxILMDc4MjQwNTUzNzExGDAWBgUqhQNkARINMTAyMDUwMDAwMjA5MzEaMBgGCCqFAwOBAwEBEgwwMDA1NDEwMTYzOTAxKTAnBgkqhkiG9w0BCQEWGnN1cHBvcnRAYmFua2tvbnRpbmVudGFsLnJ1MQswCQYDVQQGEwJSVTE1MDMGA1UECB4sADIANgAgBCEEQgQwBDIEQAQ+BD8EPgQ7BEwEQQQ6BDgEOQAgBDoEQAQwBDkxRzBFBgNVBAcePgQzAC4AIAQWBDUEOwQ1BDcEPQQ+BDIEPgQ0BEEEOgAgBD8EPgRBAC4AIAQYBD0EPgQ3BDUEPARGBDUEMgQ+MTMwMQYDVQQKHioEGgQRACAAIgQaBD4EPQRCBDgEPQQ1BD0EQgQwBDsETAAiACAEHgQeBB4xCjAIBgNVBAsTATAxMzAxBgNVBAMeKgQaBBEAIAAiBBoEPgQ9BEIEOAQ9BDUEPQRCBDAEOwRMACIAIAQeBB4EHjEvMC0GA1UECR4mBEMEOwAuACAEEwQwBDMEMARABDgEPQQwACAENAAuACAAMgAwADkxNTAzBgNVBAweLAQfBEAENQQ0BEEENQQ0BDAEQgQ1BDsETAAgBB8EQAQwBDIEOwQ1BD0EOARPMS8wLQYDVQQqHiYEIQQwBD0EQwRABDAAIAQlBDAEPQQwBEUEPAQ1BDQEPgQyBD0EMDEbMBkGA1UEBB4SBB0EMAQyBEAEQwQ3BD4EMgQwMGMwHAYGKoUDAgITMBIGByqFAwICJAAGByqFAwICHgEDQwAEQI4PFdbsM+R5o9wxGgpRyBs1yTk6swDVYfKUPI76ZqdUX8v3V25fYkzUNpFICI9LK88qs7e3Xt9w7EW+kDedv0OjggUHMIIFAzAOBgNVHQ8BAf8EBAMCBPAwJgYDVR0lBB8wHQYIKwYBBQUHAwQGByqFAwICIgYGCCsGAQUFBwMCMB0GA1UdDgQWBBQW/vMC1690XuMSa7WOVq3fw4yPfzCCAYwGA1UdIwSCAYMwggF/gBQEHsJXPlt+Fvgg9tLrDRnT/Faw5aGCAVOkggFPMIIBSzEYMBYGBSqFA2QBEg0xMDIxNjAyODU1MjYyMRowGAYIKoUDA4EDAQESDDAwMTY1NTA0NTQwNjEmMCQGA1UECQwd0YPQuy4g0JouINCd0LDRgdGL0YDQuCDQtC4gMjgxGzAZBgkqhkiG9w0BCQEWDGNhQHRheG5ldC5ydTELMAkGA1UEBhMCUlUxMzAxBgNVBAgMKjE2INCg0LXRgdC/0YPQsdC70LjQutCwINCi0LDRgtCw0YDRgdGC0LDQvTEVMBMGA1UEBwwM0JrQsNC30LDQvdGMMR4wHAYDVQQKDBXQl9CQ0J4g0KLQsNC60YHQndC10YIxMDAuBgNVBAsMJ9Cj0LTQvtGB0YLQvtCy0LXRgNGP0Y7RidC40Lkg0YbQtdC90YLRgDEjMCEGA1UEAwwa0KPQpiDQl9CQ0J4g0KLQsNC60YHQndC10YKCECguGZo2SlOrRVDRZFHylakwgaoGA1UdHwSBojCBnzBNoEugSYZHaHR0cDovL2NhLnRheG5ldC5ydS9yYS9jZHAvMDQxZWMyNTczZTViN2UxNmY4MjBmNmQyZWIwZDE5ZDNmYzU2YjBlNS5jcmwwTqBMoEqGSGh0dHA6Ly9jYTIudGF4bmV0LnJ1L3JhL2NkcC8wNDFlYzI1NzNlNWI3ZTE2ZjgyMGY2ZDJlYjBkMTlkM2ZjNTZiMGU1LmNybDCBuwYIKwYBBQUHAQEEga4wgaswUwYIKwYBBQUHMAKGR2h0dHA6Ly9jYS50YXhuZXQucnUvcmEvY2RwLzA0MWVjMjU3M2U1YjdlMTZmODIwZjZkMmViMGQxOWQzZmM1NmIwZTUuY2VyMFQGCCsGAQUFBzAChkhodHRwOi8vY2EyLnRheG5ldC5ydS9yYS9jZHAvMDQxZWMyNTczZTViN2UxNmY4MjBmNmQyZWIwZDE5ZDNmYzU2YjBlNS5jZXIwKwYDVR0QBCQwIoAPMjAxMzA3MTcxMjMwMDBagQ8yMDE0MDcxNzEyMzAwMFowEwYDVR0gBAwwCjAIBgYqhQNkcQEwNgYFKoUDZG8ELQwrItCa0YDQuNC/0YLQvtCf0YDQviBDU1AiICjQstC10YDRgdC40Y8gMy42KTCCATMGBSqFA2RwBIIBKDCCASQMKyLQmtGA0LjQv9GC0L7Qn9GA0L4gQ1NQIiAo0LLQtdGA0YHQuNGPIDMuNikMUyLQo9C00L7RgdGC0L7QstC10YDRj9GO0YnQuNC5INGG0LXQvdGC0YAgItCa0YDQuNC/0YLQvtCf0YDQviDQo9CmIiDQstC10YDRgdC40LggMS41DE/QodC10YDRgtC40YTQuNC60LDRgiDRgdC+0L7RgtCy0LXRgtGB0YLQstC40Y8g4oSWINCh0KQvMTIxLTE4NTkg0L7RgiAxNy4wNi4yMDEyDE/QodC10YDRgtC40YTQuNC60LDRgiDRgdC+0L7RgtCy0LXRgtGB0YLQstC40Y8g4oSWINCh0KQvMTI4LTE4MjIg0L7RgiAwMS4wNi4yMDEyMAgGBiqFAwICAwNBAIbQ5zuOUs0s/1alo7IWLBu77PKrh9IG7O2Sk0BmWxmgOmT7uFGg0gsQjzV3F6AueGOcNN//FPmF6AmSdF3hZaYxggPhMIID3QIBATCCAVswggFLMRgwFgYFKoUDZAESDTEwMjE2MDI4NTUyNjIxGjAYBggqhQMDgQMBARIMMDAxNjU1MDQ1NDA2MSYwJAYDVQQJDB3Rg9C7LiDQmi4g0J3QsNGB0YvRgNC4INC0LiAyODEbMBkGCSqGSIb3DQEJARYMY2FAdGF4bmV0LnJ1MQswCQYDVQQGEwJSVTEzMDEGA1UECAwqMTYg0KDQtdGB0L/Rg9Cx0LvQuNC60LAg0KLQsNGC0LDRgNGB0YLQsNC9MRUwEwYDVQQHDAzQmtCw0LfQsNC90YwxHjAcBgNVBAoMFdCX0JDQniDQotCw0LrRgdCd0LXRgjEwMC4GA1UECwwn0KPQtNC+0YHRgtC+0LLQtdGA0Y/RjtGJ0LjQuSDRhtC10L3RgtGAMSMwIQYDVQQDDBrQo9CmINCX0JDQniDQotCw0LrRgdCd0LXRggIKF1D1SQAAAAAoKTAKBgYqhQMCAgkFAKCCAh0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTMxMDE4MDc0NjI3WjAvBgkqhkiG9w0BCQQxIgQgq2X4XaPCvKD9QAfeneWq0Z/2NPXSPaAw1s9d/KDGesUwggGwBgsqhkiG9w0BCRACLzGCAZ8wggGbMIIBlzCCAZMwCAYGKoUDAgIJBCBTgw9tNJVOR/4qQCheWJJMm2jp90MO0lH8Fk/PbU6ofjCCAWMwggFTpIIBTzCCAUsxGDAWBgUqhQNkARINMTAyMTYwMjg1NTI2MjEaMBgGCCqFAwOBAwEBEgwwMDE2NTUwNDU0MDYxJjAkBgNVBAkMHdGD0LsuINCaLiDQndCw0YHRi9GA0Lgg0LQuIDI4MRswGQYJKoZIhvcNAQkBFgxjYUB0YXhuZXQucnUxCzAJBgNVBAYTAlJVMTMwMQYDVQQIDCoxNiDQoNC10YHQv9GD0LHQu9C40LrQsCDQotCw0YLQsNGA0YHRgtCw0L0xFTATBgNVBAcMDNCa0LDQt9Cw0L3RjDEeMBwGA1UECgwV0JfQkNCeINCi0LDQutGB0J3QtdGCMTAwLgYDVQQLDCfQo9C00L7RgdGC0L7QstC10YDRj9GO0YnQuNC5INGG0LXQvdGC0YAxIzAhBgNVBAMMGtCj0KYg0JfQkNCeINCi0LDQutGB0J3QtdGCAgoXUPVJAAAAACgpMAoGBiqFAwICEwUABEDHVrOsITp4hULayHoVzpoIIqIU2D4EHvLa5bhYIaGva6jMmDGdHf4y8goDMnd8beyYMDwVKjUTjzhmZdO+M0IKAAAAAAAA";
 send_post("http://collatauto.demo.nbki.ru:8080/CollatAuto/collatauto",$pd," "," ");
 
?>